version: "3.9"

services:
  db:
    container_name: todo-list-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - todo-list-db:/var/lib/postgresql

volumes:
  todo-list-db:
