version: "3.9"

services:
  todo-list:
    container_name: todo-list
    image: todo-list:1.0.0
    build: .
    ports:
      - "3333:3333"
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db

  db:
    container_name: todo-list-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - todo-list-db:/var/lib/postgresql

volumes:
  todo-list-db:
